---

- name: chown and chmod librepotools-data to celery-workerq
  file:
    path: /var/local/librepotools/librepotools-data
    owner: celery-workerq
    group: celery-workerq
    mode: 0755
    recurse: yes

- name: Insert repotools.sh to set global Environment Variables
  template:
    src: repotools.sh.j2
    dest: /etc/profile.d/repotools.sh

- name: Download Repotools War file
  get_url: 
    url: https://github.com/OULibraries/LibRepoTools/releases/download/v1.0.1/kernel-api-1.0.1-SNAPSHOT-jar-with-dependencies.jar
    dest: /var/local/librepotools/kernel-api-current.jar
    owner: celery-workerq
    group: celery-workerq
    mode: 0700

- name: Download Sage Journal Issue Date file
  get_url: 
    url: https://github.com/OULibraries/LibRepoTools/releases/download/v1.0.2/sageJournalIssueDateInfo.json
    dest: /var/local/librepotools/librepotools-data/sageJournalIssueDateInfo.json
    owner: celery-workerq
    group: celery-workerq
    mode: 0700
